### ISSUE TITLE
Settings command

### ISSUE THREAD

**Issue by TimStewartJ** [a-outs/GunrockJS#3]
The current implementation of the settings command features the ability to enable/disable commands per-guild.

**TODO:**

- [x] Make help messages reflect command settings.
- [x] Prevent disabling settings and help commands
- [x] Prefix setting
- [x] Ephemeral response settings?
- [ ] Permission settings
- [ ] Guild-wide slash command enabling
- [ ] Guild-wide regular command enabling

**Comment by TimStewartJ** [comment]
Ephemerality can now be set per command and guild-wide.
